apiVersion: apps/v1
kind: Deployment
metadata:
  name: applications-router
  labels:
    app: applications-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applications-router
  template:
    metadata:
      labels:
        app: applications-router
    spec:
      containers:
      - name: web
        image: msull92/applications-router:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: msull92-com-load-balancer
spec:
  selector:
    app: applications-router
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
